#!/bin/bash


version=1.0.3
cubature=cubature-${version}
cubaturesrc=`ls cubature/pcubature.c`

# download if necessary
if [[ x$cubaturesrc == x ]];
then
    mkdir -p cubature
    cd cubature
    wget https://github.com/stevengj/cubature/archive/v${version}.tar.gz
    tar -xzf v${version}.tar.gz
    rm v${version}.tar.gz
    mv cubature-${version}/* .
    rm -rf cubature-${version}
fi
