#!/bin/bash
version=1.0

rm -rf DYRes-v${version}
wget http://pcteserver.mi.infn.it/~ferrera/codes/dyres-v${version}.tgz
tar -xzf dyres-v${version}.tgz
rm dyres-v${version}.tgz

cp DYRes-v${version}/src/*/* .
