      INTEGER KN, NF

      INTEGER NMAX
      DOUBLE COMPLEX NA,S

      COMMON / NNUSED / NMAX
      COMMON / MOMS   / NA (NDIM)
!$OMP THREADPRIVATE(/MOMS/)
      COMMON / HSUMS  / S(NDIM,6)
!$OMP THREADPRIVATE(/HSUMS/)
